// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fuqlwkhucfbhpjlmxaeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1cWx3a2h1Y2ZiaHBqbG14YWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MjQ3MjEsImV4cCI6MjA5MTUwMDcyMX0.FGWxFTwCWeeitNYThZnrGVQj85I1_SWgU6M39S8bo5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);